name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs :
  check-bets-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/stepup-node@v3
        with:
          node-version: '14'
      - run: npm install -g bats
      - run: bats -v
